symfonycasts_sass:
    sass_options:
        # Permet aux `@use`/`@import` des vendors (Bootstrap…) de résoudre
        load_path:
            - '%kernel.project_dir%/node_modules'
        quiet_deps: true

        embed_source_map: true
