volumes:
  composercache:
  globalcache:
  php-socket:

services:
  php:
    build:
      context: .
      target: app_php
      args:
        COMPOSER_GITHUB_TOKEN: ${COMPOSER_GITHUB_TOKEN:-}
    environment:
      - SSH_AUTH_SOCK=${SSH_AUTH_SOCK}
    volumes:
      - .:/srv
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
      - composercache:/.composer
      - globalcache:/.cache
      - ~/.ssh:/ssh-host/:ro
      - php-socket:/var/run/php
    tty: true

  slides:
    image: marpteam/marp-cli:v4.4.0
    environment:
      - LANG=$LANG
    volumes:
      - .:/home/marp/app
    ports:
      - '8080:8080'
      - '37717:37717'
    command: --watch --server

  nginx:
    build:
      context: .
      target: app_nginx
    ports:
      - '8000:80'
      - '443:443'
    depends_on:
      - php
    volumes:
      - .:/srv
      - php-socket:/var/run/php

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - '8025:8025'
      - '1025:1025'
