server {
    listen 80;
    server_name slides.remij.dev;

    root /var/www/remij.dev/current/slides/;
    index README.html;

    location / {
        try_files $uri $uri/ $uri/README.html =404;
    }
}
